### ISSUE TITLE
User can create a new job

### ISSUE THREAD

**Issue by nsturz** [nsturz/production-sheet#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 - User will be able to view their jobs on the "Production sheet" page after filling out a "New Job" form. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User presses the green "New Job" button
- The "New Job" form modal appears. User fills out the form. 
- When user pushes "save", the modal disappears, and the new job populates onto the "Production Sheet" page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="452" alt="Screen Shot 2023-03-08 at 4 14 24 PM" src="https://user-images.githubusercontent.com/94485412/224866508-058c375e-e284-4430-bae2-c5654c940186.png">

<img width="528" alt="Screen Shot 2023-03-08 at 4 14 45 PM copy" src="https://user-images.githubusercontent.com/94485412/233185643-6b1fcf2f-8001-42d8-8818-3c29f330d3ac.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create all applicable tables and rows from the DB Designer Schema.
- [x] Update `data.sql` to insert all applicable data so that one job may be displayed with all appropriate job data.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create an `app.post` method that posts a new job to the database. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Install Bootstrap 5 into the head of `index.html`.
- [x] Install ReactStrap with `npm install reactstrap react react-dom`
- [x] Install the "Lato" font from Google Fonts into the head of `index.html`. Use Bold 700, Regular 400, and Light 300
- [x] Create a page called `production-sheet.jsx`
- [x] Style the page to look like the wireframe. 
- [x] Create functionality that allows the job information to populate once the page loads.
- [x] Create a component called `new-job-form.jsx`
- [x] Style it like the wireframe.
- [x] Inside `NewJobForm...`
- [x] Give the `form` element a prop of `onSubmit={  } `
- [x] Use `useState` React hook to create an initial state for `values`, and pass in an object with the following properties and values: 
  - [x] year
  - [x] week
  - [x] companyName
  - [x] jobNumber
  - [x] paperDetails
  - [x] shippingStatus, paymentStatus, otherStatus
  - [x] distributorCopies, storeCopies, officeCopies
  - [x] instructions
  - [x] shipDate, dudeDate, inHomeDate
  - [x] headline
  - [x] address
  - [x] city, state, zip
- [x] Define a `handle_____Change(event)` method for each item in state above, and in each functions code block,  set the value of each item to equal `event.target.value` 
- [x] Define a `handleSubmit(event)`  function that does the following: 
- [x] Call the `preventDefault()` method of the `event` object
- [x] Create a new JavaScript object called `newJob`, and give it properties and values that correspond with the values in state.
- [ ] Call 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
