### ISSUE TITLE
User can view a list of jobs based on certain criteria. 

### ISSUE THREAD

**Issue by nsturz** [nsturz/production-sheet#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 - User will be able to view whichever jobs they have already entered, based on which week of which year it lands in. 
 - For instance, user can view all jobs created in "week 2" of "2023", and so on and so forth. 
 - Right now, the app only displays one job. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

 - User selects the "week" and "year" options on the dropdown elements. 
 - User clicks "search"
 - If there are jobs for that week, a list of them is rendered onto the page. 
 - If there are no jobs yet, user sees a message stating that there are no jobs for that week of that year. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="548" alt="Screen Shot 2023-04-19 at 1 06 40 PM" src="https://user-images.githubusercontent.com/94485412/233188037-c6dd337a-dda0-418a-9672-e5faa5e4b1b2.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create a new `app.get()` function that GETS all jobs based on `weekId` and `yearId`
- [x] Order jobs by `jobNumber` (chronologically)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `<ProductionSheet />` to have a new item in state called `jobs`
- [x] Define a function called `searchJobs` that FETCHes all jobs that have the same week AND year id's, when the user presses "search" 
- [x] - [ ]  Wrap the "year", "week", and "search" elements at the top of the page in a `<form />` element, with the button type being switched to "submit". 
- [x] Give the newly created `<form />` element an `onSubmit` prop with a value of `searchJobs`
- [x] Inside the `return` method, update the `<ul />` element to conditionally render either a message stating that there a re "no jobs", or render a list of the jobs. 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
