### ISSUE TITLE
User can update job information

### ISSUE THREAD

**Issue by nsturz** [nsturz/production-sheet#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1029" alt="Screen Shot 2023-04-26 at 11 53 35 AM" src="https://user-images.githubusercontent.com/94485412/234675095-067284e6-d702-44e6-b4c5-c431012fa4ed.png">

<img width="1030" alt="Screen Shot 2023-04-26 at 11 54 22 AM" src="https://user-images.githubusercontent.com/94485412/234675128-55fa9d31-0a91-40ec-bdac-2828a33b79d0.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create a new `app.patch` method that UPDATES jobs in the database. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a functional component called `EditModal`.
- [x] Style it to look like the wireframe (but make it say "edit modal" instead, obviously)
- [x] Update `ProductionSheet` so that each edit icon triggers the edit modal to appear.
- [x] Update `ProductionSheet` so that when the edit icon of a particular job is clicked, the edit modal populates with that job's information.
- [x] When user clicks "save", the information is updated in the server.
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
