### ISSUE TITLE
User can cancel a job. 

### ISSUE THREAD

**Issue by nsturz** [nsturz/production-sheet#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to delete a job if they wish. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User clicks on the "trash" icon for the job they wish to cancel. 
- A modal appears, asking user if they wish to confirm their choice. 
- If user clicks cancel, modal disappears and nothing happens. 
- If user clicks confirm, the job is moved to a different page, where all cancelled jobs can be viewed. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="564" alt="Screen Shot 2023-05-04 at 11 23 21 AM" src="https://user-images.githubusercontent.com/94485412/236294774-f69b2fdb-03f9-4a4d-8f20-517bcac304e0.png">

<img width="531" alt="Screen Shot 2023-05-04 at 11 45 05 AM" src="https://user-images.githubusercontent.com/94485412/236299628-b535ca2c-6834-418f-87e9-13dedcd4c1a5.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to  create an `app.delete` function that deletes one job based on the `jobId` criteria. 
- [x] Create an `app.post()` function that POSTS the selected job to the database.
- [x]  Make sure all of the same columns as "jobs", and the` jobId` needs to **STAY THE SAME!!!!**
- [x] Update database design so that all jobs have an `isCancelled` column, which is initially set to false, and when the user cancels a job, becomes `UPDATED` to true. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a React functional component called `DeleteJobModal` and style it like the wireframe. Make sure it goes in the "components" folder. 
- [x] Createb a React functional component called `CancelledJobs` and style it like the wireframe. Make sure it goes in the "pages" folder. 
- [x] Create functionality to delete a job from the database, and remove it from the `jobs` array in `ProductionSheet`. 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
